name: Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Run unit tests
        run: go test -short ./...
